# # Use Node
# FROM node:18

# # Create app directory
# WORKDIR /app

# # Copy package files
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy all source
# COPY . .

# # Build the Next.js app
# RUN npm run build

# # Expose port
# EXPOSE 3000

# # Start the app
# CMD ["npm", "start"]
# Use Node
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Overwrite ENV for docker build
ARG NEXT_PUBLIC_AUTH_URL
ENV NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
